---
# files: roles/consul/tasks/consul.yml

- name: Download Consul x64
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip
    dest=~/consul.zip
    force=no
  when: ansible_architecture == "x86_64"

- name: Download Consul x32
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/0.5.0_linux_386.zip
    dest=~/consul.zip
    force=no
  when: ansible_architecture == "i386"

- name: Download Consul Web UI
  get_url:
    url=https://dl.bintray.com/mitchellh/consul/0.5.0_web_ui.zip
    dest=~/consul_ui.zip
    force=no

- name: Create Consul directories
  file:
    path={{ item }}
    state=directory
  with_items:
    - /etc/consul.d
    - /var/log/consul
    - /var/consul
    - /var/www/consul

- name: Extract Consul
  unarchive:
    src=~/consul.zip
    dest=/usr/local/bin
    creates=/usr/local/bin/consul
    copy=false

- name: Extract Consul Web UI
  unarchive:
    src=~/consul_ui.zip
    dest=/var/www/consul
    creates=/var/www/consul/dist/index.html
    copy=false
