---
# files: roles/security/tasks/fail2ban.yml

- name: Install fail2ban
  apt:
    name=fail2ban
    state=latest
  notify:
    - restart fail2ban

- name: Configure fail2ban
  copy:
    src=etc/fail2ban/jail.local
    dest=/etc/fail2ban/jail.local
    mode=0644
  notify:
    - restart fail2ban
