---
# file: roles/mysql/tasks/mysql.yml

- name: Install MySQL
  apt:
    name={{ item }}
    state=latest
  with_items:
    - mysql-server-5.6
    - php5-mysql
    - python-mysqldb
  notify:
    - restart php

- name: Update MySQL root password for all root accounts
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy my.cnf file with root password credentials
  template:
    src=root/my.cnf
    dest=/root/.my.cnf
    mode=0600
  notify:
    - restart mysql
