---
# file: roles/common/tasks/vim.yml

- name: Install vim
  apt:
    name=vim
    state=latest

- name: Copy vimrc
  sudo: no
  template:
    src=../files/vimrc
    dest=~/.vimrc
    mode=0664

- name: Assures ~/.vim/autoload exists
  sudo: no
  file:
    path=~/.vim/autoload
    state=directory

- name: Install pathogen
  sudo: no
  get_url:
    url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest=~/.vim/autoload/pathogen.vim
    mode=0664
    force=no
