---
# file: roles/common/tasks/vim.yml

- name: Install vim
  apt:
    name=vim
    state=latest

- name: Copy vimrc
  sudo: no
  copy:
    src=vimrc
    dest=~/.vimrc
    mode=0664

- name: Assures ~/.vim directories exist
  sudo: no
  file:
    path={{ item }}
    state=directory
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle

- name: Install pathogen
  sudo: no
  get_url:
    url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest=~/.vim/autoload/pathogen.vim
    mode=0664
    force=no

- name: Install vim-javascript
  sudo: no
  git: repo=git@github.com:pangloss/vim-javascript.git
       dest=~/.vim/bundle/vim-javascript

- name: Install vim-jsx
  sudo: no
  git: repo=git@github.com:mxw/vim-jsx.git
       dest=~/.vim/bundle/vim-jsx
