---
# file: roles/docker/tasks/docker.yml

- name: Add docker key
  apt_key:
    keyserver=hkp://keyserver.ubuntu.com:80
    id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add docker source
  copy:
    src=etc/apt/sources.list.d/docker.list
    dest=/etc/apt/sources.list.d/docker.list

- name: Install docker
  apt:
    name=lxc-docker
    state=latest
    update_cache=yes
