---
# file: roles/php/tasks/php.yml

- name: Install PHP
  apt:
    name={{ item }}
    state=latest
  with_items:
    - php5
    - php5-mcrypt
    - php5-cli
    - php5-curl
    - php5-common
    - php5-fpm
    - php5-mongo

- name: Configure php-fpm
  copy:
   src=etc/php5/fpm/php.ini
   dest=/etc/php5/fpm/php.ini
  notify:
    - restart php

- name: Configure nginx vhost
  copy:
    src=etc/nginx/sites-available/default
    dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx
